// Meta Data -> Title + Description --- SEO ---
// components/Layout.js
import React from 'react';
import Header from './Header';
import Footer from './Footer';
import 'bootstrap/dist/css/bootstrap.min.css'

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};
const Layout = ({ children }) => {
  return (
    <>
      <Header />
      <main className="container mt-4">
        {children}
      </main>
      <Footer />
    </>
  );
};

export default Layout;

